# celmedia_toyocosta_vehiculos_homepage:
#     pattern:  /hello/{name}
#     defaults: { _controller: CelmediaToyocostaVehiculosBundle:Default:index }

toyocosta_homepage:
    pattern:  /
    defaults: { _controller: CelmediaToyocostaVehiculosBundle:Default:index }

ver_vehiculo:
    path:      /vehiculos/{vehiculoid}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:verVehiculo }

empresa:
    path:      /empresa
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:empresa }

mantenimiento:
    path:      /mantenimiento
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:mantenimiento }

test_drive:
    path:      /testdrive
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:test }

recursos_humanos:
    path:      /rrhh
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:rrhh }

contactenos:
    path:      /contacto
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:contactenos }

envio_contacto:
    path:      /enviando
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:envioContacto }

certificados:
    path:      /certificados
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:certificados }

landing:
    path:      /landing
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:landing }