# celmedia_toyocosta_vehiculos_homepage:
#     pattern:  /hello/{name}
#     defaults: { _controller: CelmediaToyocostaVehiculosBundle:Default:index }

toyocosta_homepage:
    pattern:  /
    defaults: { _controller: CelmediaToyocostaVehiculosBundle:Default:index }

autos:
    path:      /autos
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:autos }
camionetas:
    path:      /camionetas
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:camionetas }
suv:
    path:      /todoterreno
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:suv }
# hibridos:
#     path:      /hibridos
#     defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:hibridos }

ver_vehiculo:
    path:      /vehiculos/{vehname}/{vehiculoid}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:verVehiculo }

empresa:
    path:      /empresa
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:empresa }

mantenimiento:
    path:      /mantenimiento
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:mantenimiento }

mantenimiento_servicio:
    path:      /mantenimiento/{servicioid}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:mantenimientoXServicio }


test_drive:
    path:      /testdrive
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:test }
    options:
        expose: true

recursos_humanos:
    path:      /rrhh
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:rrhh }

contactenos:
    path:      /contacto
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:contactenos }
    options:
        expose: true

contactenos_agencia:
    path:      /contacto/{agenciaid}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:contactenosXAgencia }
    options:
        expose: true

certificados:
    path:      /certificados
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:certificados }



envio_mantenimiento:
    path:      /mantenimientoenvio
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:envioMantenimiento }
    options:
        expose: true

envio_contacto:
    path:      /enviando/form
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:envioContacto }
    options:
        expose: true

envio_rrhh:
    path:      /rrhh/form
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:envioRrhh }
    options:
        expose: true

envio_rrhh_adjunto:
    path:      /rrhh/adjunto
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:ajaxUploadFormData }
    options:
        expose: true

# envio_test:
#     path:      /testdrive/form
#     defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:envioTestDrive }
#     options:
#         expose: true

envio_cotizacion:
    path:      /vehiculo/cotizacion
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:envioCotizacion }
    options:
        expose: true





get_taller:
    path:      /getTaller
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:getTaller }
    options:
        expose: true

consultar_precio:
    path:      /vehiculo/precio
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:consultarPreciosXModelo }
    options:
        expose: true

consultar_plazo:
    path:      /vehiculo/preciofinal
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:consultarPreciosFinales }
    options:
        expose: true
consultar_obsequios:
    path:      /obsequios
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:consultarObsequios }
    options:
        expose: true

especificacion:
    path:      /vehiculo/especificacion/{vehiculoid}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:especificacion }

# ROUTING MOVIL

m_vehiculo:
    path:      /vehiculo/{vehname}/{vehiculoid}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:verVehiculo }

m_cotizar:
    path:       /cotizar
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:cotizarVehiculo }

m_cotizar_vehiculo:
    path:       /cotizar/{vehname}/{vehiculoid}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:cotizarVehiculoxId }

m_pirelli:
    path:       /distribuidor/pirelli
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:pirelli }

m_montacargas:
    path:       /montacarga
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:montacargas }

m_infopirelli:
    path:       /informacion-pirelli
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:infoPirelli }

m_citamantenimiento:
    path:       /cita-mantenimiento
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:mantenimiento }

m_testdrive:
    path:       /test-drive
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:testdrive }

m_contacto:
    path:       /contactenos
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:contactenos }


# LANDING PAGES

landingseo:
    path:      /landing/etiqueta-seowebmaster
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:etiquetaSeo }

landinginnvento:
    path:      /landing/etiqueta-innvento
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:etiquetaInnvento }

landingbumeran:
    path:      /landing/etiqueta-bumeran
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:etiquetaBumeran }

landingurbano:
    path:      /landing/etiqueta-urbano
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:etiquetaUrbano }

landingface:
    path:      /landing/etiqueta-facebook
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:etiquetaFacebook }

landinggoogle:
    path:      /landing/etiqueta-google
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:etiquetaGoogle }


envio_landing:
    path:      /landing/form
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:envioLanding }
    options:
        expose: true

# MAILING

mailing:
    path:      /mailing/etiqueta-roja
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:mailingEtiqueta }