# celmedia_toyocosta_vehiculos_homepage:
#     pattern:  /hello/{name}
#     defaults: { _controller: CelmediaToyocostaVehiculosBundle:Default:index }

toyocosta_homepage:
    pattern:  /
    defaults: { _controller: CelmediaToyocostaVehiculosBundle:Default:index }

autos:
    path:      /autos-toyota
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:autos }
camionetas:
    path:      /camionetas-toyota
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:camionetas }
suv:
    path:      /todoterreno-toyota
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:suv }
# hibridos:
#     path:      /hibridos
#     defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:hibridos }

ver_vehiculo:
    path:      /{categoria}/Toyota/{vehname}/{vehiculoid}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:verVehiculo }

empresa:
    path:      /empresa
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:empresa }

mantenimiento:
    path:      /mantenimiento
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:mantenimiento }

mantenimiento_servicio:
    path:      /mantenimiento/{servicioid}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:mantenimientoXServicio }

exonerados:
    path:      /exonerados
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:exonerados }

exonerados_informacion:
    path:      /exonerados/informacion/{tipo}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:exoneradosImpuestos }


test_drive:
    path:      /testdrive
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:test }
    options:
        expose: true

recursos_humanos:
    path:      /rrhh
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:rrhh }

contactenos:
    path:      /contacto
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:contactenos }
    options:
        expose: true

contactenos_agencia:
    path:      /contacto/{agenciaid}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:contactenosXAgencia }
    options:
        expose: true

certificados:
    path:      /certificados
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:certificados }



envio_mantenimiento:
    path:      /mantenimientoenvio
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:envioMantenimiento }
    options:
        expose: true

envio_contacto:
    path:      /enviando/form
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:envioContacto }
    options:
        expose: true

envio_rrhh:
    path:      /rrhh/form
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:envioRrhh }
    options:
        expose: true

envio_rrhh_adjunto:
    path:      /rrhh/adjunto
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:ajaxUploadFormData }
    options:
        expose: true

# envio_test:
#     path:      /testdrive/form
#     defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:envioTestDrive }
#     options:
#         expose: true

envio_cotizacion:
    path:      /vehiculo/cotizacion
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:envioCotizacion }
    options:
        expose: true





get_taller:
    path:      /getTaller
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:getTaller }
    options:
        expose: true

consultar_precio:
    path:      /vehiculo/precio
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:consultarPreciosXModelo }
    options:
        expose: true

consultar_plazo:
    path:      /vehiculo/preciofinal
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:consultarPreciosFinales }
    options:
        expose: true
consultar_obsequios:
    path:      /obsequios
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:consultarObsequios }
    options:
        expose: true

especificacion:
    path:      /{categoria}/Toyota/{vehname}/{vehiculoid}/especificacion
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:especificacion }

# ROUTING MOVIL

m_vehiculo:
    path:      /vehiculo/{vehname}/{vehiculoid}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:verVehiculo }

m_cotizar:
    path:       /cotizar
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:cotizarVehiculo }

m_cotizar_vehiculo:
    path:       /cotizar/{vehname}/{vehiculoid}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:cotizarVehiculoxId }

m_pirelli:
    path:       /distribuidor/pirelli
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:pirelli }

m_montacargas:
    path:       /montacarga
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:montacargas }

m_citamantenimiento:
    path:       /cita-mantenimiento
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:mantenimiento }

m_testdrive:
    path:       /test-drive
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:testdrive }

m_contacto:
    path:       /contactenos
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:contactenos }

m_envio_contactenos:
    path:      /enviando/contactenos
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:enviarContactenos }
    options:
        expose: true

m_envio_test:
    path:      /enviando/testdrive
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:enviarTest }
    options:
        expose: true

m_envio_cita:
    path:      /enviando/cita
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:enviarCita }
    options:
        expose: true

m_envio_cotizacion:
    path:      /enviando/cotizacion
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mobile:enviarCotizacion }
    options:
        expose: true


# LANDING PAGES

landingseo:
    path:      /landing/etiqueta-seowebmaster
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:etiquetaSeo }

landinginnvento:
    path:      /landing/etiqueta-innvento
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:etiquetaInnvento }

landingbumeran:
    path:      /landing/etiqueta-bumeran
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:etiquetaBumeran }

landingurbano:
    path:      /landing/etiqueta-urbano
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:etiquetaUrbano }

landingface:
    path:      /landing/etiqueta-facebook
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:etiquetaFacebook }

landinggoogle:
    path:      /landing/etiqueta-google
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:etiquetaGoogle }

# Landings 17/11/2014

landing_rent_bumeran:
    path:      /landing/rent-bumeran
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:rentBumeran }

landing_rav_seo:
    path:      /landing/rav-seowebmaster
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:ravSeowebmaster }

landing_yaris_soluciones:
    path:      /landing/yaris-soluciones
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:yarisSoluciones }

landing_yaris_invento:
    path:      /landing/yaris-invento
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:yarisInvento }

landing_seminuevo_bumeran:
    path:      /landing/seminuevo-bumeran
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:seminuevoBumeran }

landing_navidad_banner:
    path:      /landing/navidad
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:navidadBanner }

# Landings 01/12/2014

landing_financiamiento_face:
    path:      /landing/financiamiento-face
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:financiamientoFace }

landing_navidad_face:
    path:      /landing/navidad-face
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:navidadFace }

# Landings 08/12/2014

landing_nav_green:
    path:      /landing/navidad-green
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:navGreen }

landing_nav_seo:
    path:      /landing/navidad-seo
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:navSeo }

landing_nav_black:
    path:      /landing/navidad-black
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:navBlack }

landing_nav_ceo:
    path:      /landing/navidad-ceo
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:navCeo }

# Landings 10/12/2014

landing_fin_black:
    path:      /landing/finan-black
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:finanBlack }

landing_fin_sol:
    path:      /landing/finan-soluciones
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:finanSol }


# Landing para red social
landing_rs:
    path:      /landing/navidad-toyota
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:rs }


# Landings 10/12/2014

landing_compra:
    path:      /landing/compra-usados
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:compraUsados }

landing_compra_bumeran:
    path:      /landing/compra-bumeran
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:compraBumeran }

landing_compra_facebook:
    path:      /landing/compra-face
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:compraFacebook }

landing_compra_google:
    path:      /landing/compra-google
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:compraGoogle }

landing_compra_black:
    path:      /landing/compra-black
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:compraBlack }


landing_movilidad:
    path:      /landing/movilidad
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:movilidad }


# Landings 18/03/2015

landing_cf_bumeran:
    path:      /landing/compra-confiable-bumeran
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:confiableBumeran }

landing_cf_data:
    path:      /landing/compra-confiable-data
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:confiableData }

landing_cf_patio:
    path:      /landing/compra-confiable-patio
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:confiablePatio }

landing_cf_autos:
    path:      /landing/compra-confiable-autos
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:confiableAutos }

landing_cf_face:
    path:      /landing/compra-confiable-facebook
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:confiableFace }

landing_cf_universo:
    path:      /landing/compra-confiable-universo
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:confiableUniverso }


landing_cm_usados:
    path:      /landing/compra-confiable-usados
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:confiableUsados }

landing_exonerados:
    path:      /landing/exonerados
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:exonerados }

landing_info_pirelli:
    path:      /landing/pirelli
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:pirelli }



envio_landing:
    path:      /landing/form
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:envioLanding }
    options:
        expose: true

# MAILING

mailing:
    path:      /mailing/etiqueta-roja
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:mailingEtiqueta }

mailing_cuotas:
    path:      /mailing/cuotas
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:mailingCuotas }

mailing_navidad:
    path:      /mailing/toyota-navidad
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Landing:mailingNavidad }

mailing_venta:
    path:      /mailing/venta
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Mailing:mailingVenta }