# celmedia_toyocosta_vehiculos_homepage:
#     pattern:  /hello/{name}
#     defaults: { _controller: CelmediaToyocostaVehiculosBundle:Default:index }

toyocosta_homepage:
    pattern:  /
    defaults: { _controller: CelmediaToyocostaVehiculosBundle:Default:index }

ver_vehiculo:
    path:      /vehiculos/{vehiculo}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:verVehiculo }

empresa:
    path:      /empresa
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:empresa }

mantenimiento:
    path:      /mantenimiento
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:mantenimiento }

test_drive:
    path:      /test
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:test }

recursos_humanos:
    path:      /rrhh
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:rrhh }

contactenos:
    path:      /contactenos
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:contactenos }