# celmedia_toyocosta_vehiculos_homepage:
#     pattern:  /hello/{name}
#     defaults: { _controller: CelmediaToyocostaVehiculosBundle:Default:index }

toyocosta_homepage:
    pattern:  /
    defaults: { _controller: CelmediaToyocostaVehiculosBundle:Default:index }

ver_vehiculo:
    path:      /vehiculos/{vehiculo}
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:verVehiculo }

empresa:
    path:      /empresa
    defaults:  { _controller: CelmediaToyocostaVehiculosBundle:Default:empresa }