parameters:
#    celmedia_toyocosta_vehiculos.example.class: Celmedia\Toyocosta\VehiculosBundle\Example
    my_user_provider.class: Celmedia\Toyocosta\VehiculosBundle\Provider\FOSUBUserProvider

services:
#    celmedia_toyocosta_vehiculos.example:
#        class: %celmedia_toyocosta_vehiculos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebookUid , twitter: twitterUid}]

    celmedia_toyocosta_vehiculos.admin.vehiculo:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\VehiculoAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\Vehiculo, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Vehiculos", label: Vehiculo}

    celmedia_toyocosta_vehiculos.admin.vehiculo_colores:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\VehiculoColoresAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\VehiculoColores, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Vehiculos", label: Vehiculo Colores}

    celmedia_toyocosta_vehiculos.admin.categoria_vehiculo:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\CategoriaVehiculoAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\CategoriaVehiculo, CelmediaToyocostaVehiculosBundle:CategoriaVehiculoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Vehiculos", label: Categorias}

    # celmedia_toyocosta_vehiculos.admin.vehiculo_galeria:
    #     class: Celmedia\Toyocosta\VehiculosBundle\Admin\VehiculoGaleriaAdmin
    #     arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\VehiculoGaleria, CelmediaToyocostaVehiculosBundle:VehiculoGaleriaAdmin, SonataAdminBundle:CRUD]
    #     tags:
    #         - {name: sonata.admin, manager_type: orm, group: "Vehiculos", label: Galeria}
    #     calls:
    #         - [ setTranslationDomain, [Celmedia\Toyocosta\VehiculosBundle]]

    celmedia_toyocosta_vehiculos.admin.vehiculo_modelos:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\VehiculoModelosAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\VehiculoModelos, CelmediaToyocostaVehiculosBundle:VehiculoModelosAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Vehiculos", label: Modelos}

    celmedia_toyocosta_vehiculos.admin.slide_principal:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\SlidePrincipalAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\SlidePrincipal, CelmediaToyocostaVehiculosBundle:SlidePrincipalAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Contenido", label: Banners Publicitarios}

    celmedia_toyocosta_vehiculos.admin.slide_vehiculos:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\SlideVehiculosAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\SlideVehiculos, CelmediaToyocostaVehiculosBundle:SlideVehiculosAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Vehiculos", label: Slide de Vehiculos}

    # celmedia_toyocosta_vehiculos.admin.modelo_especificaciones:
    #     class: Celmedia\Toyocosta\VehiculosBundle\Admin\ModeloEspecificacionesAdmin
    #     arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\ModeloEspecificaciones, SonataAdminBundle:CRUD]
    #     tags:
    #         - {name: sonata.admin, manager_type: orm, group: "Vehiculos", label: Especificaciones de Modelos}

    celmedia_toyocosta_vehiculos.admin.plazo:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\PlazoAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\Plazo, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Vehiculos", label: Plazo}

    celmedia_toyocosta_vehiculos.admin.vehiculo_especificacion:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\VehiculoEspecificacionAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\VehiculoEspecificacion, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Vehiculos", label: Especificaciones de Vehiculo}
