parameters:
#    celmedia_toyocosta_vehiculos.example.class: Celmedia\Toyocosta\VehiculosBundle\Example

services:
#    celmedia_toyocosta_vehiculos.example:
#        class: %celmedia_toyocosta_vehiculos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    celmedia_toyocosta_vehiculos.admin.vehiculo:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\VehiculoAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\Vehiculo, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Vehiculo}

    celmedia_toyocosta_vehiculos.admin.vehiculo_colores:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\VehiculoColoresAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\VehiculoColores, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: VehiculoColores}

    celmedia_toyocosta_vehiculos.admin.categoria_vehiculo:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\CategoriaVehiculoAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\CategoriaVehiculo, CelmediaToyocostaVehiculosBundle:CategoriaVehiculoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: CategoriaVehiculo}

    celmedia_toyocosta_vehiculos.admin.vehiculo_galeria:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\VehiculoGaleriaAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\VehiculoGaleria, CelmediaToyocostaVehiculosBundle:VehiculoGaleriaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: VehiculoGaleria}

    celmedia_toyocosta_vehiculos.admin.vehiculo_modelos:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\VehiculoModelosAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\VehiculoModelos, CelmediaToyocostaVehiculosBundle:VehiculoModelosAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: VehiculoModelos}

    celmedia_toyocosta_vehiculos.admin.slide_principal:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\SlidePrincipalAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\SlidePrincipal, CelmediaToyocostaVehiculosBundle:SlidePrincipalAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: SlidePrincipal}

    celmedia_toyocosta_vehiculos.admin.slide_vehiculos:
        class: Celmedia\Toyocosta\VehiculosBundle\Admin\SlideVehiculosAdmin
        arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\SlideVehiculos, CelmediaToyocostaVehiculosBundle:SlideVehiculosAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: SlideVehiculos}

    # celmedia_toyocosta_vehiculos.admin.modelo_especificaciones:
    #     class: Celmedia\Toyocosta\VehiculosBundle\Admin\ModeloEspecificacionesAdmin
    #     arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\ModeloEspecificaciones, CelmediaToyocostaVehiculosBundle:ModeloEspecificacionesAdmin]
    #     tags:
    #         - {name: sonata.admin, manager_type: orm, group: admin, label: ModeloEspecificaciones}

    # celmedia_toyocosta_vehiculos.admin.vehiculo_especificaciones_detalle:
    #     class: Celmedia\Toyocosta\VehiculosBundle\Admin\VehiculoEspecificacionesDetalleAdmin
    #     arguments: [~, Celmedia\Toyocosta\VehiculosBundle\Entity\VehiculoEspecificacionesDetalle, CelmediaToyocostaVehiculosBundle:VehiculoEspecificacionesDetalleAdmin]
    #     tags:
    #         - {name: sonata.admin, manager_type: orm, group: admin, label: VehiculoEspecificacionesDetalle}
