Celmedia\Toyocosta\ContenidoBundle\Entity\Establecimiento:
    type: entity
    table: establecimiento
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 140
            nullable: false
        horario:
            type: text
            nullable: false
        ubicacion:
            type: string
            length: 250
            nullable: false
        latitud:
            type: string
            length: 50
            nullable: false
        longuitud:
            type: string
            length: 50
            nullable: false
        telefono:
            type: integer
            unsigned: false
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]