Celmedia\Toyocosta\ContenidoBundle\Entity\InfoContacto:
    type: entity
    table: info_contacto
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 140
            nullable: false
        apellido:
            type: string
            length: 140
            nullable: false
        telefono:
            type: integer
            unsigned: false
            nullable: false
        email:
            type: string
            length: 200
            nullable: false
        ciudad:
            type: string
            length: 250
            nullable: false
        area:
            type: string
            length: 250
            nullable: false
        observaciones:
            type: text
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]