Celmedia\Toyocosta\ContenidoBundle\Entity\TipoReserva:
    type: entity
    table: tipo_reserva
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 200
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    manyToMany:
      talleres:
        targetEntity: Establecimiento
        joinTable:
            name: tipo_reserva_establecimiento
            joinColumns:
              reserva_id:
                referencedColumnName: id
            inverseJoinColumns:
              establecimiento_id:
                referencedColumnName: id
        cascade: ["persist"]

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]