Celmedia\Toyocosta\ContenidoBundle\Entity\Variables:
    type: entity
    table: variables
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        concepto:
            type: string
            length: 140
            nullable: false
        entrada_minima:
            type: float
            unsigned: false
            nullable: false
        interes:
            type: float
            unsigned: false
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]