celmedia_toyocosta_montacargas_homepage:
    path:     /hello/{name}
    defaults: { _controller: CelmediaToyocostaMontacargasBundle:Default:index }

montacargas_home:
    path:      /montacargas
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:principal }

montacargas_postventa:
    path:      /montacargas/postventa
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:postVenta }

montacargas_renta:
    path:      /montacargas/renta
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:renta }

montacargas_sas:
    path:      /montacargas/sas
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:tecnologiaSas }

montacargas_usados:
    path:      /montacargas/usados
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:usados }

envio_exitoso:
    pattern:  /montacargas/mensaje
    defaults: { _controller: CelmediaToyocostaMontacargasBundle:Default:mensaje }

montacargas_contacto:
    pattern:  /montacargas/contacto
    defaults: { _controller: CelmediaToyocostaMontacargasBundle:Default:monContacto }

montacargas_cotizacion:
    path:      /montacargas/{categoria}/{modelo}/{idmontacarga}/cotizacion
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:cotizacion }

usados_cotizacion:
    path:      /montacargas/usado/{idusado}
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:cotizacionUsado }

ver_montacarga:
    path:      /montacargas/{categoria}/{modelo}/{montacargaid}
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:producto }


