celmedia_toyocosta_montacargas_homepage:
    path:     /hello/{name}
    defaults: { _controller: CelmediaToyocostaMontacargasBundle:Default:index }

montacargas_home:
    path:      /montacargas
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:principal }

montacargas_postventa:
    path:      /montacargas/postventa
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:postVenta }

montacargas_renta:
    path:      /montacargas/renta
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:renta }

montacargas_sas:
    path:      /montacargas/sas
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:tecnologiaSas }

montacargas_usados:
    path:      /montacargas/usados
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:usados }

ver_montacarga:
    path:      /montacargas/{montacargaid}
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:producto }

montacargas_cotizacion:
    path:      /montacargas/cotizacion
    defaults:  { _controller: CelmediaToyocostaMontacargasBundle:Default:cotizacion }
