Celmedia\Toyocosta\MotosBundle\Entity\Moto:
    type: entity
    table: moto
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 140
            nullable: false
        precio:
            type: float
            nullable: false
        informacion:
            type: text
            nullable: false
        imagen_banner:
            type: text
            nullable: false
        ficha:
            type: text
            nullable: true
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
    oneToMany:
      colores:
        targetEntity: MotoColor
        mappedBy: moto
        cascade: ["persist"]

    manyToOne:
      categoria:
        targetEntity: MotoCategoria
        inversedBy: motos
        joinColumn:
          name: categoria_id
          referencedColumnName: id

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]