Celmedia\Toyocosta\MotosBundle\Entity\MotoCategoria:
    type: entity
    table: moto_categoria
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 140
            nullable: false
        imagen_thumb:
            type: text
            nullable: false
        logo_home:
            type: text
            nullable: false
        logo_hover:
            type: text
            nullable: false
        descripcion:
            type: text
            nullable: true
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    oneToMany:
        motos:
            targetEntity: Moto
            mappedBy: categoria

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]