Celmedia\Toyocosta\MontacargasBundle\Entity\MontacargaUsado:
    type: entity
    table: montacarga_usado
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        modelo:
            type: string
            length: 140
            nullable: false
        precio:
            type: float
            nullable: false
        anio:
            type: integer
            nullable: false
        descripcion:
            type: text
            nullable: true
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    oneToMany:
      galeria:
        targetEntity: MontacargaUsadoGaleria
        mappedBy: montacarga_usado
        cascade: ["persist"]

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]