Celmedia\Toyocosta\MontacargasBundle\Entity\Montacarga:
    type: entity
    table: montacarga
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        modelo:
            type: string
            length: 140
            nullable: false
        precio:
            type: float
            nullable: false
        caracteristicas:
            type: text
            nullable: false
        formato:
            type: text
            nullable: true
        rawText:
            type: text
            nullable: true
        ficha:
            type: text
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    oneToMany:        
      galeria:
        targetEntity: MontacargaGaleria
        mappedBy: montacarga_galeria
        cascade: ["persist"]
      # file:
      #   targetEntity: Application\Sonata\MediaBundle\Entity\Media
      #   mappedBy: montacarga
      #   orderBy:
      #      position: ASC
    # oneToOne:
    #   file:
    #     targetEntity: Application\Sonata\MediaBundle\Entity\Media
    #     cascade: ["persist"]
    #     joinColumn:
    #       name: media_id
    #       referencedColumnName: id
    manyToOne:
      montacarga_subcategoria:
        targetEntity: Subcategoria
        inversedBy: montacargas
        joinColumn:
          name: subcategoria_id
          referencedColumnName: id
    manyToMany:
      imagenes:
        targetEntity: Application\Sonata\MediaBundle\Entity\GalleryHasMedia
        joinTable:
          name: montacarga_imagen
          joinColumns:
            id_montacarga:
              referencedColumnName: id
          inverseJoinColumns:
            id_imagen:
              referencedColumnName: id
              unique: true
        cascade: ["persist"]


    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]