Celmedia\Toyocosta\MontacargasBundle\Entity\Montacarga:
    type: entity
    table: montacarga
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        modelo:
            type: string
            length: 140
            nullable: false
        precio:
            type: float
            nullable: false
        caracteristicas:
            type: text
            nullable: false
        ficha:
            type: text
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    oneToMany:        
      galeria:
        targetEntity: MontacargaGaleria
        mappedBy: montacarga_galeria
        cascade: ["persist"]

    manyToOne:
      montacarga_subcategoria:
        targetEntity: Subcategoria
        inversedBy: montacargas
        joinColumn:
          name: subcategoria_id
          referencedColumnName: id


    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]