Celmedia\Toyocosta\MontacargasBundle\Entity\Subcategoria:
    type: entity
    table: subcategoria_montacarga
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 140
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        created_at:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated_at:
            type: datetime
            gedmo:
              timestampable:
                on: update

    oneToMany:        
      montacargas:
        targetEntity: Montacarga
        mappedBy: montacarga_subcategoria
        cascade: ["persist"]

    manyToOne:
      montacarga_categoria:
        targetEntity: CategoriaMontacarga
        inversedBy: subcategorias
        joinColumn:
          name: categoria_id
          referencedColumnName: id

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]