# Acme/DemoBundle/Resources/config/admin.yml
services:
    sonata.admin.post:
        class: Celmedia\Toyocosta\PirelliBundle\Admin\LlantaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Pirelli", label: "Llantas" }
        arguments:
            - ~
            - Celmedia\Toyocosta\PirelliBundle\Entity\Llanta
            - ~
        calls:
            - [ setTranslationDomain, [CelmediaToyocostaPirelliBundle]]

    celmedia_toyocosta_pirelli.admin.distribuidor:
        class: Celmedia\Toyocosta\PirelliBundle\Admin\DistribuidorAdmin
        arguments: [~, Celmedia\Toyocosta\PirelliBundle\Entity\Distribuidor, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Pirelli", label: Distribuidores}
