# pirelli_home:
#     pattern:  /index
#     defaults: { _controller: CelmediaToyocostaPirelliBundle:Default:index }

pirelli_home:
    pattern:  /pirelli
    defaults: { _controller: CelmediaToyocostaPirelliBundle:Default:index }



pirelli_camioneta:
    pattern:  /pirelli/camioneta
    defaults: { _controller: CelmediaToyocostaPirelliBundle:Default:camionetaPirelli }

pirelli_suv:
    pattern:  /pirelli/suv
    defaults: { _controller: CelmediaToyocostaPirelliBundle:Default:suvPirelli }

pirelli_industrial:
    pattern:  /pirelli/industrial
    defaults: { _controller: CelmediaToyocostaPirelliBundle:Default:industrialPirelli }

pirelli_camion:
    pattern:  /pirelli/camion
    defaults: { _controller: CelmediaToyocostaPirelliBundle:Default:camionPirelli }

pirelli_buscador:
    pattern:  /pirelli/buscando
    defaults: { _controller: CelmediaToyocostaPirelliBundle:Default:buscadorPirelli }

pirelli_filtro:
    pattern:  /filtro
    defaults: { _controller: CelmediaToyocostaPirelliBundle:Default:filtroBuscadorPirelli }

pirelli_informacion:
    pattern:  /pirelli/{{modelo}}/{id_llanta}/informacion
    defaults: { _controller: CelmediaToyocostaPirelliBundle:Default:informacionPirelli }

pirelli_distribuidores:
    pattern: /pirelli/distribuidores
    defaults: { _controller: CelmediaToyocostaPirelliBundle:Default:distribuidoresPirelli}

pirelli_envio_info:
    pattern: /enviando
    defaults: { _controller: CelmediaToyocostaPirelliBundle:Default:envioInfoPirelli}
    options:
        expose: true

pirelli_mensaje:
    pattern: /mensaje-enviado
    defaults: { _controller: CelmediaToyocostaPirelliBundle:Default:mensajePirelli}
    options:
        expose: true
