celmedia_toyocosta_contenido:
    resource: "@CelmediaToyocostaContenidoBundle/Resources/config/routing.yml"
    prefix:   /

celmedia_toyocosta_montacagas:
    resource: "@CelmediaToyocostaMontacagasBundle/Resources/config/routing.yml"
    prefix:   /

celmedia_toyocosta_vehiculos:
    resource: "@CelmediaToyocostaVehiculosBundle/Resources/config/routing.yml"
    prefix:   /


celmedia_toyocosta_pirelli:
    resource: "@CelmediaToyocostaPirelliBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile



fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"