Celmedia\Toyocosta\SeminuevoBundle\Entity\SeminuevoGaleria:
    type: entity
    table: seminuevo_galeria
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        imagen:
            type: text
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    manyToOne:
      seminuevo_galeria:
        targetEntity: Seminuevo
        inversedBy: galeria
        joinColumn:
          name: seminuevo_id
          referencedColumnName: id

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]