Celmedia\Toyocosta\SeminuevoBundle\Entity\SeminuevoColores:
    type: entity
    table: seminuevo_colores
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 140
            nullable: false
        valor:
            type: string
            length: 7
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    oneToMany:
      seminuevo_color:
        targetEntity: Seminuevo
        mappedBy: colores
        cascade: ["persist"]

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]