celmedia_toyocosta_seminuevo_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:index }

seminuevos_home:
    pattern:  /seminuevos
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:seminuevos }

seminuevos_venda_usado:
    pattern:  /vendausado
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:vendausado }

seminuevos_estado_usado:
    pattern:  /estadousado
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:estadousado }

seminuevos_buscador:
    pattern:  /buscando
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:buscadorSeminuevos }

seminuevos_filtro:
    pattern:  /filtro
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:filtroBuscadorSeminuevos }

seminuevos_register:
    pattern:  /seminuevos/register
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Security:register }

registro_exitoso:
    pattern:  /mensaje/user
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Security:mensajeUser }

login:
    path:     /login
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Security:login }


login_check:
    path: /login_check

logout:
    path: /logout