celmedia_toyocosta_seminuevo_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:index }

seminuevos_home:
    pattern:  /seminuevos
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:seminuevos }

seminuevos_venda_usado:
    pattern:  /seminuevos/venda
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:vendausado }

seminuevos_estado_usado:
    pattern:  /seminuevos/estado
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:estadousado }

seminuevos_buscador:
    pattern:  /seminuevosbs
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:buscadorSeminuevos }

seminuevos_cotizador:
    path:      /seminuevos/cotizador/{seminuevoid}
    defaults:  { _controller: CelmediaToyocostaSeminuevoBundle:Default:cotizadorSN }


envio_cotizacion_sm:
    path:      /seminuevo/enviocotizacion
    defaults:  { _controller: CelmediaToyocostaSeminuevoBundle:Default:envioCotizacion }
    options:
        expose: true

consultar_plazo_sm:
    path:      /seminuevos/cotizadorsm
    defaults:  { _controller: CelmediaToyocostaSeminuevoBundle:Default:consultarPreciosFinales }
    options:
        expose: true

seminuevos_filtro:
    pattern:  /filtro
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:filtroBuscadorSeminuevos }

seminuevos_register:
    pattern:  /seminuevos/register
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Security:register }

registro_exitoso:
    pattern:  /seminuevos/mensaje
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Security:mensajeUser }

envio_usado:
    pattern:  /seminuevo/envio
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:envioUsado }
    options:
        expose: true

login:
    path:     /login
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Security:login }


login_check:
    path: /login_check

logout:
    path: /logout