celmedia_toyocosta_seminuevo_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:index }

seminuevos_home:
    pattern:  /seminuevos
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:seminuevos }

seminuevos_venda_usado:
    pattern:  /vendausado
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:vendausado }

seminuevos_estado_usado:
    pattern:  /estadousado
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:estadousado }

seminuevos_buscador:
    pattern:  /buscando
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:buscadorSeminuevos }

seminuevos_filtro:
    pattern:  /filtro
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:filtroBuscadorSeminuevos }

seminuevos_register:
    pattern:  /user/register
    defaults: { _controller: CelmediaToyocostaSeminuevoBundle:Default:registerSeminuevos }