parameters:
#    celmedia_toyocosta_seminuevo.example.class: Celmedia\Toyocosta\SeminuevoBundle\Example

services:
#    celmedia_toyocosta_seminuevo.example:
#        class: %celmedia_toyocosta_seminuevo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    celmedia_toyocosta_seminuevo.admin.seminuevo:
        class: Celmedia\Toyocosta\SeminuevoBundle\Admin\SeminuevoAdmin
        arguments: [~, Celmedia\Toyocosta\SeminuevoBundle\Entity\Seminuevo, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 'Seminuevo', label: Seminuevo}

    celmedia_toyocosta_seminuevo.admin.seminuevo_certificado:
        class: Celmedia\Toyocosta\SeminuevoBundle\Admin\SeminuevoCertificadoAdmin
        arguments: [~, Celmedia\Toyocosta\SeminuevoBundle\Entity\SeminuevoCertificado, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 'Seminuevo', label: Certificados}

    celmedia_toyocosta_seminuevo.admin.seminuevo_galeria:
        class: Celmedia\Toyocosta\SeminuevoBundle\Admin\SeminuevoGaleriaAdmin
        arguments: [~, Celmedia\Toyocosta\SeminuevoBundle\Entity\SeminuevoGaleria, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 'Seminuevo', label: Galeria}
