Celmedia\Toyocosta\PirelliBundle\Entity\Distribuidor:
    type: entity
    table: pirelli_distribuidor
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 200
            nullable: false
        direccion:
            type: string
            length: 200
            nullable: false
        ciudad:
            type: string
            length: 140
            nullable: false
        telefono:
            type: integer
            nullable: false
        contacto:
            type: string
            length: 140
            nullable: false
        latitud:
            type: string
            length: 50
            nullable: false
        longuitud:
            type: string
            length: 50
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]