Celmedia\Toyocosta\VehiculosBundle\Entity\ModeloEspecificaciones:
    type: entity
    table: modelo_especificaciones
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        categoria:
            type: string
            length: 140
            nullable: false
        nombre:
            type: string
            length: 140
            nullable: false
        valor:
            type: text
            nullable: false

    manyToOne:
      modelo:
        targetEntity: VehiculoModelos
        inversedBy: especificaciones
        joinColumn:
          name: vehiculo_modelo_id
          referencedColumnName: id

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]