Celmedia\Toyocosta\VehiculosBundle\Entity\SlideVehiculos:
    type: entity
    table: slide_vehiculos
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        imagen_slide:
            type: text
            nullable: false
        imagen_thumb:
            type: text
            nullable: true
        logo:
            type: text
            nullable: true
        menu_posicion:
            type: integer
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    manyToOne:
      categoria_vehiculo:
        targetEntity: CategoriaVehiculo
        inversedBy: slides
        joinColumn:
          name: categoria_id
          referencedColumnName: id
      vehiculo_slide:
        targetEntity: Vehiculo
        inversedBy: slides_vehiculos
        joinColumn:
          name: vehiculo_id
          referencedColumnName: id

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]