Celmedia\Toyocosta\VehiculosBundle\Entity\Vehiculo:
    type: entity
    table: vehiculo
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 140
            nullable: false
        precio:
            type: float
            nullable: false
        precio_neto:
            type: float
            nullable: false
        informacion:
            type: text
            nullable: false
        descripcion:
            type: text
            nullable: false
        imagen_banner:
            type: text
            nullable: false
        imagen_thumb:
            type: text
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    oneToMany:
      colores:
        targetEntity: VehiculoColores
        mappedBy: vehiculo
        cascade: ["persist"]
      galeria:
        targetEntity: VehiculoGaleria
        mappedBy: vehiculogaleria
        cascade: ["persist"]
      modelos:
        targetEntity: VehiculoModelos
        mappedBy: vehiculomodel
      slides_vehiculos:
        targetEntity: SlideVehiculos
        mappedBy: vehiculo_slide


    manyToOne:
      categoria:
        targetEntity: CategoriaVehiculo
        inversedBy: vehiculos
        joinColumn:
          name: categoria_id
          referencedColumnName: id


    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]