Celmedia\Toyocosta\VehiculosBundle\Entity\VehiculoCotizacion:
    type: entity
    table: vehiculo_cotizacion
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 140
            nullable: false
        apellido:
            type: string
            length: 140
            nullable: false
        email:
            type: string
            length: 200
            nullable: false
        cedula:
            type: integer
            length: 10
            nullable: false
        telefono:
            type: integer
            nullable: true
        ciudad:
            type: string
            length: 140
            nullable: false
        mensaje:
            type: text
            nullable: false
        valor_entrada:
            type: float
            nullable: false
        interes_vehiculo:
            type: float
            nullable: false
        interes_entrada:
            type: float
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    manyToOne:
      vehiculo_modelo:
        targetEntity: VehiculoModelos
        inversedBy: cotizaciones
        joinColumn:
          name: vehiculo_id
          referencedColumnName: id
      plazo:
        targetEntity: Plazo
        inversedBy: formcotizaciones
        joinColumn:
          name: plazo_id
          referencedColumnName: id

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]