Celmedia\Toyocosta\VehiculosBundle\Entity\VehiculoColores:
    type: entity
    table: vehiculo_colores
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        imagen_color:
            type: text
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
    manyToOne:
        vehiculo:
          targetEntity: Vehiculo
          inversedBy: colores
          joinColumn:
            name: vehiculo_id
            referencedColumnName: id
        coloresvehiculo:
          targetEntity: Celmedia\Toyocosta\ContenidoBundle\Entity\Color
          inversedBy: vehiculo_color
          joinColumn:
            name: color_id
            referencedColumnName: id

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]