Celmedia\Toyocosta\VehiculosBundle\Entity\Vehiculo:
    type: entity
    table: vehiculo
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 140
            nullable: false
        precio:
            type: float
            nullable: false
        precio_neto:
            type: float
            nullable: false
        informacion:
            type: text
            nullable: false
        descripcion:
            type: text
            nullable: false
        imagen_banner:
            type: text
            nullable: false
        imagen_thumb:
            type: text
            nullable: false
        ficha:
            type: text
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update

    oneToMany:
      colores:
        targetEntity: VehiculoColores
        mappedBy: vehiculo
        cascade: ["persist"]

      galeria:
        targetEntity: VehiculoGaleria
        mappedBy: vehiculogaleria
        cascade: ["persist"]

      modelos:
        targetEntity: VehiculoModelos
        mappedBy: vehiculomodel
        cascade: ["persist"]

      slides_vehiculos:
        targetEntity: SlideVehiculos
        mappedBy: vehiculo_slide

      especificaciones:
        targetEntity: VehiculoEspecificacion
        mappedBy: vehiculo_especificacion
        cascade: ["persist"]

    manyToOne:
      categoria:
        targetEntity: CategoriaVehiculo
        inversedBy: vehiculos
        joinColumn:
          name: categoria_id
          referencedColumnName: id
    manyToMany:
      plazos:
        targetEntity: Plazo
        joinTable:
            name: vehiculo_plazo
            joinColumns:
              plazo_id:
                referencedColumnName: id
            inverseJoinColumns:
              vehiculo_id:
                referencedColumnName: id
        cascade: ["persist"]
      imagenes:
        targetEntity: Application\Sonata\MediaBundle\Entity\GalleryHasMedia
        joinTable:
          name: vehiculo_imagen
          joinColumns:
            id_vehiculo:
              referencedColumnName: id
          inverseJoinColumns:
            id_imagen:
              referencedColumnName: id
              unique: true
        cascade: ["persist"]

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]