Celmedia\Toyocosta\VehiculosBundle\Entity\VehiculoEspecificacionesDetalle:
    type: entity
    table: vehiculo_especificaciones_detalle
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 140
            nullable: false
        valor:
            type: text
            nullable: false

    manyToOne:
      modeloespecificacion:
        targetEntity: ModeloEspecificaciones
        inversedBy: detalles
        joinColumn:
          name: modelo_especificacion_id
          referencedColumnName: id

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]