Celmedia\Toyocosta\MontacagasBundle\Entity\MontacargaUsadoGaleria:
    type: entity
    table: montacarga_usado_galeria
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        foto:
            type: text
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        created_at:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated_at:
            type: datetime
            gedmo:
              timestampable:
                on: update

    manyToOne:
      montacarga_usado:
        targetEntity: MontacargaUsado
        inversedBy: galeria
        joinColumn:
          name: montacarga_usado_id
          referencedColumnName: id

    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]